### ISSUE TITLE
Revolt event loop hangs with file operations inside defer()

### ISSUE THREAD

**Issue by evll** [amphp/fs#78]
Not sure, if it's related to https://github.com/amphp/file/issues/75 , but the script below is just hanging indefinitely (writing succeeds):

```php
\Revolt\EventLoop::defer(function () {
    \Amp\File\write('/code/out', 'contents');
});

\Revolt\EventLoop::run();
```

The same version without `defer()` works fine:

```php
\Amp\File\write('/code/out', 'contents');

\Revolt\EventLoop::run();
```

**Comment by trowski** [comment]
I believe this was fixed with `amphp/parallel@v2.2.5`. If not, feel free to repoen.
